spring:
  application:
    name: config-server      profiles:    active:    - native
    
server:  port: 8888
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/